.PHONY: clean All

All:
	@echo "----------Building project:[ nios_first - Release ]----------"
	@cd "nios_first" && "$(MAKE)" -f  "nios_first.mk" && "$(MAKE)" -f  "nios_first.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ nios_first - Release ]----------"
	@cd "nios_first" && "$(MAKE)" -f  "nios_first.mk" clean
