.PHONY: clean All

All:
	@echo "----------Building project:[ 12 - Debug ]----------"
	@cd "12" && "$(MAKE)" -f  "12.mk" && "$(MAKE)" -f  "12.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ 12 - Debug ]----------"
	@cd "12" && "$(MAKE)" -f  "12.mk" clean
