.PHONY: clean All

All:
	@echo "----------Building project:[ nios_hello - Debug ]----------"
	@cd "ppp" && "$(MAKE)" -f  "nios_hello.mk" && "$(MAKE)" -f  "nios_hello.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ nios_hello - Debug ]----------"
	@cd "ppp" && "$(MAKE)" -f  "nios_hello.mk" clean
